[project]
name = "airband-switcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "numpy>=2.3.4",
]

[tool.ruff]
extend-exclude = [
    "**/gnuradio/**"
]
